### ISSUE TITLE
Error when setting memgpt flag to true 

### ISSUE THREAD

**Issue by IreGaddr** [PromptEngineer48/MemGPT-AutoGEN-LLM#1]
When setting USE_MEMGPT = True I get the following error when running your script. All libraries are installed. 

(wizard) PS C:\code\LLMs\wizard> & c:/code/LLMs/wizard/Scripts/python.exe c:/code/LLMs/wizard/app.py --tracemalloc

MemGPT Agent at work

User_proxy (to MemGPT_coder):

Write a Function to print Numbers 1 to 10

--------------------------------------------------------------------------------
C:\code\LLMs\wizard\lib\site-packages\memgpt\autogen\memgpt_agent.py:212: RuntimeWarning: coroutine 'AgentAsync.step' was never awaited
  (
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "c:\code\LLMs\wizard\app.py", line 76, in <module>
    user_proxy.initiate_chat(
  File "C:\code\LLMs\wizard\lib\site-packages\autogen\agentchat\conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\code\LLMs\wizard\lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send       
    recipient.receive(message, self, request_reply, silent)
  File "C:\code\LLMs\wizard\lib\site-packages\autogen\agentchat\conversable_agent.py", line 462, in receive    
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "C:\code\LLMs\wizard\lib\site-packages\autogen\agentchat\conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])       
  File "C:\code\LLMs\wizard\lib\site-packages\memgpt\autogen\memgpt_agent.py", line 212, in _generate_reply_for_user_message
    (
TypeError: cannot unpack non-iterable coroutine object

**Comment by mertdemir0** [comment]
have same issue here

**Comment by MB-Finski** [comment]
Edit the memgpt_aget.py and define the generate_reply_for_user_message method to be async. I.e. "async def generate_reply_for_user_message....".

This will fix this error.

**Comment by Dennis-Henriksen** [comment]
> Edit the memgpt_aget.py and define the generate_reply_for_user_message method to be async. I.e. "async def generate_reply_for_user_message....".
> 
> This will fix this error.

Thank you MB-Finski,

Just to elaborate a bit:

    async def _generate_reply_for_user_message(
        self,
        messages: Optional[List[Dict]] = None,
        sender: Optional[Agent] = None,
        config: Optional[Any] = None,
    ) -> Tuple[bool, Union[str, Dict, None]]:
        self.agent.interface.reset_message_list()
