### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'context_window'

### ISSUE THREAD

**Issue by MarceloEmmerich** [PromptEngineer48/MemGPT-AutoGEN-LLM#10]
Just copy & paste from the repo, install deps and run it, getting this error:

```bash
MemGPT Agent at work

User_proxy (to MemGPT_coder):

Write a Function to print Numbers 1 to 10

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marcelo/projects/agitate/app.py", line 76, in <module>
    user_proxy.initiate_chat(
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/memgpt/autogen/memgpt_agent.py", line 235, in _generate_reply_for_user_message
    ) = self.agent.step(user_message, first_message=False, skip_verify=self.skip_verify)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/memgpt/agent.py", line 657, in step
    raise e
  File "/home/marcelo/projects/agitate/venv/lib/python3.11/site-packages/memgpt/agent.py", line 587, in step
    context_window=self.config.context_window,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'context_window'```

**Comment by Matros1975** [comment]
I have the same issue.
I run model locally in LM Studio
